<?php

namespace ContainerLpuDvPM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IWR2fbhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IWR2fbh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IWR2fbh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'todo' => ['privates', '.errored..service_locator.IWR2fbh.App\\Entity\\Todo', NULL, 'Cannot autowire service ".service_locator.IWR2fbh": it needs an instance of "App\\Entity\\Todo" but this type has been excluded in "config/services.yaml".'],
        ], [
            'todo' => 'App\\Entity\\Todo',
        ]);
    }
}
