<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'show_todos' => [[], ['_controller' => 'App\\Controller\\ToDoController::index'], [], [['text', '/todos']], [], [], []],
    'create_todo' => [[], ['_controller' => 'App\\Controller\\ToDoController::create'], [], [['text', '/create']], [], [], []],
    'edit_todo' => [[], ['_controller' => 'App\\Controller\\ToDoController::edit'], [], [['text', '/edit']], [], [], []],
    'App\Controller\ToDoController::index' => [[], ['_controller' => 'App\\Controller\\ToDoController::index'], [], [['text', '/todos']], [], [], []],
    'App\Controller\ToDoController::create' => [[], ['_controller' => 'App\\Controller\\ToDoController::create'], [], [['text', '/create']], [], [], []],
    'App\Controller\ToDoController::edit' => [[], ['_controller' => 'App\\Controller\\ToDoController::edit'], [], [['text', '/edit']], [], [], []],
];
